dist: focal
arch: amd64
virt: lxd
os: linux

branches:
  only:
    - master
    - main

env:
  - CI=false TERM=xterm

before_install:
  - git checkout $TRAVIS_BRANCH

install: 
  - pwd 
  - ls 
  - chmod +x ./deploy.sh
script:
  - ./deploy.sh
